[package]
name = "bevy_stuff"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }
bevy_fpc = "0.1.3"
bevy_rapier2d = { version = "0.25.0", features = [
    "simd-stable",
    "debug-render-2d",
] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
